### ISSUE TITLE
Alterar cor de comentários em arquivos .tsx

### ISSUE THREAD

**Issue by GersonRocha9** [Thomaz-Peres/Theme#3]
Baita tema! Uso faz algum tempo já, recomendo apenas que altere a cor dos comentários em arquivos .tsx que hoje se encontra na mesma cor do código. Perceba na linha 16 e 18 quando insiro um comentário.

Link para imagem: https://uploaddeimagens.com.br/imagens/xaOPG1s

**Comment by Thomaz-Peres** [comment]
Foi mal a demora para responder, estava meio ocupado!

Fiz a alteração, espero que tenha ficado do seu agrado! So atualizar seu tema que deve funcionar! 

Obrigado pelo feedback! Estarei fechando a issue, caso tenha mais alguma alteração so avisar por aqui ou abrir uma outra!
